### ISSUE TITLE
Verify header-links.txt colors

### ISSUE THREAD

**Issue by artlogic** [arsmentis/volt-theme#2]
There are two suspicious lines in header-links.txt, first, why isn't this Volt orange?

```html
<meta name="msapplication-TileColor" content="#da532c">
```

Second - should this be Volt orange and not white?

```html
<meta name="theme-color" content="#ffffff">
```

Please look into this and let me know what you find.

**Comment by SKBruck** [comment]
This code sets the Windows 8 and 10 tile color for Windows users. It's ```#da532c``` because that's what realfavicongenerator.net auto-set it to.
```html
<meta name="msapplication-TileColor" content="#da532c">
```
Screenshots of the current orange v. Volt orange v. white:

![mstile-examples](https://cloud.githubusercontent.com/assets/2489779/18657079/ea68c0c0-7ec4-11e6-81c0-4357e9424a37.png)

This code sets the app colors on Android Chrome homescreen. Again, realfavicongenerator.net auto-set it to ```#ffffff```.
```html
 <meta name="theme-color" content="#ffffff">
```
Screenshots of the white v. Volt orange:

![chrome-white-example](https://cloud.githubusercontent.com/assets/2489779/18657138/53819c4e-7ec5-11e6-9756-d25d14fea7d5.png)
![chrome-orange-example](https://cloud.githubusercontent.com/assets/2489779/18657140/595825ca-7ec5-11e6-8680-9d6f6c0f74c6.png)

**Comment by artlogic** [comment]
`theme-color` should be Volt orange - feel free to update `header-links.txt`

**Comment by SKBruck** [comment]
I will also make the dedicated icon for mstile and set the tile color to Volt orange.

**Comment by artlogic** [comment]
Perfect. ETA?
